# Generated by Django 5.1.4 on 2025-02-07 04:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('quantity_in', models.PositiveIntegerField(default=24, verbose_name='Quantité interne ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix')),
                ('price_big_customer', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix grossiste')),
                ('alcoholic', models.BooleanField(default=False, verbose_name='Alcoolisé')),
                ('recycling', models.BooleanField(default=False, verbose_name='Reciclable')),
                ('type', models.CharField(choices=[('bouteille', 'Bouteille'), ('boite', 'Cannette'), ('carton', 'Carton')], default='bottle', max_length=10, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['name'],
            },
        ),
    ]
