# Generated by Django 5.1.4 on 2025-02-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RapidInvoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapidinvoice',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rapidinvoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
