# Generated by Django 5.1.4 on 2025-02-07 04:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255, verbose_name='Client')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('delivered', models.BooleanField(default=False, verbose_name='Livré')),
                ('status', models.IntegerField(choices=[(1, 'En cours'), (2, 'Payé'), (3, 'Annulé')], default=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice', verbose_name='Facture')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Item de facture',
                'verbose_name_plural': 'Items de facture',
            },
        ),
    ]
